update to requested changes
When trying int in resource_quota_lease_count.go we get

Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled