Fix `nil` panic with `vault_identity_group_policies`
Fixes the following possible panic

```
Stack trace from the terraform-provider-vault_v2.24.1_x4 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 166 [running]:
github.com/hashicorp/terraform-provider-vault/vault.identityGroupPoliciesRead(0xc000726b60, 0x119aa00, 0xc00071c640, 0xc000726b60, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vault/vault/resource_identity_group_policies.go:120 +0x9ac
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000278a20, 0xc000477220, 0x119aa00, 0xc00071c640, 0xc000738538, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/resource.go:460 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000286020, 0x13c3450, 0xc0007d2570, 0xc000650d80, 0xc000286020, 0xc0007d2570, 0xc0002beba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1168220, 0xc000286020, 0x13c3450, 0xc0007d2570, 0xc000650d20, 0x0, 0x13c3450, 0xc0007d2570, 0xc0009d6410, 0xc5)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00079c340, 0x13ce238, 0xc000782c00, 0xc000438800, 0xc000117470, 0x19de4b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00079c340, 0x13ce238, 0xc000782c00, 0xc000438800, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccf
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00028e170, 0xc00079c340, 0x13ce238, 0xc000782c00, 0xc000438800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5

Error: The terraform-provider-vault_v2.24.1_x4 plugin crashed!
```